# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a26d5fbea482a06d533300b3a8226ba6d2efcc06d723c6b33858a47a05747ec0e18caf14ff40bd158473d687e074875481800bc7ef6b8ac3500da5e4da86471

test:
  secret_key_base: a343c9a761511e15076b4aea71e75cadd8c46ded71f1b1e57df8f1ded9728a60e1ac1ef208dff2f91a152252673517957fb3dc452c1a3c21e737e3c576e52e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
